name: Build Project and Publish to itch.io
on: push
jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    # This stops builds that are in-progress once a new commit comes in
    concurrency: 
      group: unity-build-${{ matrix.targetPlatform }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          # - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          #- StandaloneLinux64 # Build a Linux 64-bit standalone.
          # - iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.
          - WebGL # WebGL.
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      # Cache
      - uses: actions/cache@v4
        with:
          path: ${{ matrix.targetPlatform }}
          key: ${{ matrix.targetPlatform }}
      # Build
      - name: Build for ${{ matrix.targetPlatform }}
        uses: game-ci/unity-builder@v4
        env:
          # Comment this out if you're using a pro license
          # UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          # Un-Comment the following lines if you're using a pro license
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v4
        with:
           name: ${{ matrix.targetPlatform }}
           path: build
      - name: Upload WebGL build to Itch.io
        if: ${{ matrix.targetPlatform == 'WebGL' }}
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: robotics-simulator
          ITCH_USER: skolodny
          PACKAGE: build/WebGL
  generateRelease:
    name: Generate Release
    runs-on: ubuntu-latest
    needs: buildForAllSupportedPlatforms
    steps:
    - name: version
      run: echo "test"
      id: version
    - name: release
      uses: actions/create-release@v2
      id: create_release
      with:
        draft: true
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload StandaloneOSX artifact
      uses: actions/upload-release-asset@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/StandaloneOSX.zip
        asset_name: StandaloneOSX.zip
        asset_content_type: application/zip
    - name: upload StandaloneWindows64 artifact
      uses: actions/upload-release-asset@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/StandaloneWindows64.zip
        asset_name: StandaloneWindows64.zip
        asset_content_type: application/zip
    - name: upload WebGL artifact
      uses: actions/upload-release-asset@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/WebGL.zip
        asset_name: WebGL.zip
        asset_content_type: application/zip

           
